// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMUAuNuPFAmfKYDREPITNKK8A7M_Y5ZaE',
    appId: '1:979486392768:web:81ae8582e2e132295e8825',
    messagingSenderId: '979486392768',
    projectId: 'article-f579b',
    authDomain: 'article-f579b.firebaseapp.com',
    storageBucket: 'article-f579b.appspot.com',
    measurementId: 'G-BKVLR0K3PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZXcCXC4x9ehqrUjjvb2AfpBXxtmtaHX8',
    appId: '1:979486392768:android:57a4fc0f507ed7d75e8825',
    messagingSenderId: '979486392768',
    projectId: 'article-f579b',
    storageBucket: 'article-f579b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqiZMZPLSJAl3_OD5VhmGLZeUGBcEc2LY',
    appId: '1:979486392768:ios:4957138ed590059f5e8825',
    messagingSenderId: '979486392768',
    projectId: 'article-f579b',
    storageBucket: 'article-f579b.appspot.com',
    iosClientId: '979486392768-thh9r3glvv4v5h19a4hi1ct49c2d5gjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.freelance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqiZMZPLSJAl3_OD5VhmGLZeUGBcEc2LY',
    appId: '1:979486392768:ios:4957138ed590059f5e8825',
    messagingSenderId: '979486392768',
    projectId: 'article-f579b',
    storageBucket: 'article-f579b.appspot.com',
    iosClientId: '979486392768-thh9r3glvv4v5h19a4hi1ct49c2d5gjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.freelance',
  );
}
